import { FurnitureItem, RoomDimensions, RoomTemplate, BasementStructure } from '../types';

// Default room dimensions
export const defaultRoomDimensions: RoomDimensions = {
  width: 500,
  height: 400,
  shape: 'rectangle',
  canvasWidth: 800,
  canvasHeight: 600,
};

// Pre-made basement structures
export const defaultBasementStructures: BasementStructure[] = [
  {
    id: 'basement-1',
    type: 'preset',
    imageUrl: 'https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&w=300',
    width: 300,
    height: 200,
    x: 0,
    y: 0,
    rotation: 0,
  },
  {
    id: 'basement-2',
    type: 'preset',
    imageUrl: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=300',
    width: 250,
    height: 180,
    x: 0,
    y: 0,
    rotation: 0,
  },
  {
    id: 'basement-3',
    type: 'preset',
    imageUrl: 'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=300',
    width: 280,
    height: 190,
    x: 0,
    y: 0,
    rotation: 0,
  },
];

// Default furniture items for the library
export const defaultFurnitureItems: Omit<FurnitureItem, 'id'>[] = [
  // Living Room
  {
    type: 'sofa',
    name: 'Three-Seater Sofa',
    width: 220,
    height: 95,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'living',
  },
  {
    type: 'sofa',
    name: 'Two-Seater Sofa',
    width: 180,
    height: 95,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'living',
  },
  {
    type: 'chair',
    name: 'Armchair',
    width: 85,
    height: 85,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/2082090/pexels-photo-2082090.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'living',
  },
  {
    type: 'table',
    name: 'Coffee Table',
    width: 120,
    height: 60,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/2194399/pexels-photo-2194399.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'living',
  },
  
  // Bedroom
  {
    type: 'bed',
    name: 'King Size Bed',
    width: 200,
    height: 180,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'bedroom',
  },
  {
    type: 'bed',
    name: 'Queen Size Bed',
    width: 160,
    height: 200,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'bedroom',
  },
  {
    type: 'nightstand',
    name: 'Nightstand',
    width: 45,
    height: 45,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/6758773/pexels-photo-6758773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'bedroom',
  },
  {
    type: 'dresser',
    name: 'Dresser',
    width: 120,
    height: 50,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'bedroom',
  },
  
  // Kitchen
  {
    type: 'table',
    name: 'Dining Table',
    width: 150,
    height: 90,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchen',
  },
  {
    type: 'chair',
    name: 'Dining Chair',
    width: 50,
    height: 50,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/2082092/pexels-photo-2082092.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchen',
  },
  {
    type: 'island',
    name: 'Kitchen Island',
    width: 120,
    height: 65,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/6198659/pexels-photo-6198659.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchen',
  },
  {
    type: 'refrigerator',
    name: 'Refrigerator',
    width: 75,
    height: 75,
    x: 0,
    y: 0,
    rotation: 0,
    imageUrl: 'https://images.pexels.com/photos/6996041/pexels-photo-6996041.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchen',
  },
];

// Room templates
export const defaultRoomTemplates: RoomTemplate[] = [
  {
    id: 'living-small',
    name: 'Small Living Room',
    dimensions: {
      width: 400,
      height: 350,
      shape: 'rectangle',
      canvasWidth: 800,
      canvasHeight: 600,
    },
    thumbnail: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
  {
    id: 'bedroom-standard',
    name: 'Standard Bedroom',
    dimensions: {
      width: 350,
      height: 400,
      shape: 'rectangle',
      canvasWidth: 800,
      canvasHeight: 600,
    },
    thumbnail: 'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
  {
    id: 'kitchen-medium',
    name: 'Medium Kitchen',
    dimensions: {
      width: 300,
      height: 350,
      shape: 'rectangle',
      canvasWidth: 800,
      canvasHeight: 600,
    },
    thumbnail: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
  {
    id: 'master-suite',
    name: 'Master Suite',
    dimensions: {
      width: 500,
      height: 450,
      shape: 'rectangle',
      canvasWidth: 1000,
      canvasHeight: 800,
    },
    thumbnail: 'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
  {
    id: 'office-home',
    name: 'Home Office',
    dimensions: {
      width: 300,
      height: 300,
      shape: 'rectangle',
      canvasWidth: 800,
      canvasHeight: 600,
    },
    thumbnail: 'https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
  {
    id: 'bathroom-small',
    name: 'Small Bathroom',
    dimensions: {
      width: 200,
      height: 250,
      shape: 'rectangle',
      canvasWidth: 600,
      canvasHeight: 500,
    },
    thumbnail: 'https://images.pexels.com/photos/6032282/pexels-photo-6032282.jpeg?auto=compress&cs=tinysrgb&w=300',
  },
];